# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  google_maps_javascript_api_key:
  secret_key_base: 8e6714e51960b775975d44486cfa23c6c39ed7d7daefe2ee8f0f7d1e9580388ab362e42cec152d3e3bc8a168ef0c639f2d5ab6b4437e9684d8269c6abd18b498

test:
  google_maps_javascript_api_key: 
  secret_key_base: cf6556dadc0267ef75e113f68e1c0c0b1e9470edd95752b3f14e2240d7dc791f1145b9436ea49e7246155b543bdfae8f94c61304ddada687ba6b5c55ed798cf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  google_maps_javascript_api_key: <%= ENV["GOOGLE_MAPS_JAVASCRIPT_API_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  google_maps_javascript_api_key: <%= ENV["GOOGLE_MAPS_JAVASCRIPT_API_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
